all:
	ipython season.py ./figs/ GEN
	ipython sens_chart.py ./figs/ GEN
	ipython npod_trade.py ./figs/ GEN
	ipython solarlat.py ./figs/ GEN
	ipython tablegen.py
	ipython tau_trade.py ./figs/ GEN
	ipython battsolarcon.py ./figs/ GEN
